exec sp_helpdb AIMS_UAT
GO

USE master;  
CREATE DATABASE SNAP_AIMS_UAT
ON
( NAME = AIMS_Prod,
FILENAME= 'D:\Database\Snapshot\SNAP_AIM_UAT.snap')
AS SNAPSHOT OF AIMS_UAT


USE master; 
RESTORE DATABASE AIMS_UAT 
FROM DATABASE_SNAPSHOT = 'SNAP_AIMS_UAT';  
GO

USE master; 
DROP Database SNAP_AIMS_UAT
GO